### ISSUE TITLE
undefined method

### ISSUE THREAD

**Issue by quinarnold** [chef-cookbooks/omnibus_updater#92]
I'm using omnibus_updater to upgrade from chef from 11.12.4 to 12.5.1 and I'm getting the following error:
## NoMethodError

undefined method `sensitive' for Chef::Resource::Execute

I'm using version 1.0.5 of omnibus_updater

This worked fine on vagrant, but fails on the dev box.

Here is my role:

{
  "name": "etl_node",
  "description": "etl node",
  "json_class": "Chef::Role",
  "default_attributes": {
  },
  "override_attributes": {
    "omnibus_updater": {
      "version": "12.5.1"
    }
  },
  "chef_type": "role",
  "run_list": [
    "recipe[omnibus_updater]",
    "recipe[tdwallet]"
  ],
  "env_run_lists": {
  }
}

Here is a snippet from the tdwallet recipe

```
# copy the necessary scripts to the above directory
node[:script].each do |key, filename|
    Chef::Log.info("Copying #{filename} to #{node[:target][:dir]}")
    cookbook_file "#{node[:target][:dir]}/#{filename}" do
        sensitive true
        source "#{filename}"
        owner 'root'
        group 'root'
        mode '0755'
        action :create
    end
end
```

**Comment by rmoriz** [comment]
`sensitive` attribute was introduced in https://github.com/chef/chef/commit/cee94f52d52806885fbd63d63addc3708b25f409 (11.14.0)

See https://github.com/DataDog/chef-datadog/issues/184 for a workaround

**Comment by tas50** [comment]
Closing as this isn't actually an omnibus_updater bug
